=== beefviper/XMLGameEngine/games/assets/xmlgameengine.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="game">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="window">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required" />
						<xs:attribute name="width" type="xs:unsignedShort" use="required" />
						<xs:attribute name="height" type="xs:unsignedShort" use="required" />
						<xs:attribute name="background" type="xs:string" use="required" />
						<xs:attribute name="fullscreen" type="xs:boolean" use="required" />
						<xs:attribute name="framerate" type="xs:unsignedByte" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="variables">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="variable">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required" />
									<xs:attribute name="value" type="xs:unsignedShort" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="objects">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="object">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="sprite">
											<xs:complexType>
												<xs:attribute name="src" type="xs:string" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="position">
											<xs:complexType>
												<xs:attribute name="x" type="xs:string" use="required" />
												<xs:attribute name="y" type="xs:string" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="velocity">
											<xs:complexType>
												<xs:attribute name="x" type="xs:string" use="required" />
												<xs:attribute name="y" type="xs:string" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="collisions">
											<xs:complexType>
												<xs:sequence minOccurs="0">
													<xs:element maxOccurs="unbounded" name="collision">
														<xs:complexType>
															<xs:attribute name="edge" type="xs:string" use="optional" />
															<xs:attribute name="basic" type="xs:string" use="optional" />
															<xs:attribute name="action" type="xs:string" use="required" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="enabled" type="xs:boolean" use="required" />
												<xs:attribute name="group" type="xs:boolean" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element minOccurs="0" name="actions">
											<xs:complexType>
												<xs:sequence>
													<xs:element maxOccurs="unbounded" name="action">
														<xs:complexType>
															<xs:attribute name="name" type="xs:string" use="required" />
															<xs:attribute name="value" type="xs:string" use="required" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element minOccurs="0" name="variables">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="variable">
														<xs:complexType>
															<xs:attribute name="score" type="xs:unsignedByte" use="required" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required" />
									<xs:attribute name="class" type="xs:string" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="states">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="state">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="shows">
											<xs:complexType>
												<xs:sequence>
													<xs:element maxOccurs="unbounded" name="show">
														<xs:complexType>
															<xs:attribute name="object" type="xs:string" use="required" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="inputs">
											<xs:complexType>
												<xs:sequence>
													<xs:element maxOccurs="unbounded" name="input">
														<xs:complexType>
															<xs:attribute name="button" type="xs:string" use="required" />
															<xs:attribute name="action" type="xs:string" use="required" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element minOccurs="0" name="conditions">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="condition">
														<xs:complexType>
															<xs:attribute name="class" type="xs:string" use="required" />
															<xs:attribute name="variable" type="xs:string" use="required" />
															<xs:attribute name="value" type="xs:unsignedByte" use="required" />
															<xs:attribute name="action" type="xs:string" use="required" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== beefviper/XMLGameEngine/games/breakout.xml
<!-- breakout.xml -->
<!-- XML Game Engine -->
<!-- author: beefviper -->
<!-- date: Sept 18, 2020 -->

<game xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="assets/xmlgameengine.xsd">
  <window name="Breakout" width="1280" height="720" background="color.black" fullscreen="false" framerate="60" />
  <variables>
    <variable name="margin" value="30" />
    <variable name="ball.radius" value="10" />
    <variable name="width" value="150" />
    <variable name="height" value="30" />
    <variable name="step" value="2" />
  </variables>
  <objects>
    <object name="ball">
      <sprite src="shape.circle(ball.radius)" />
      <position x="window.width.center - ball.radius" y="window.bottom - margin * 3" />
      <velocity x="random.range(-3,3)" y="random.range(-7,-5)" />
      <collision enabled="true" top="collide('bounce')" bottom="collide('bounce')" left="collide('bounce')" right="collide('bounce')" basic="collide('bounce')" />
    </object>
    <object name="player">
      <sprite src="shape.rectangle(width,height)" />
      <position x="window.width.center" y="window.bottom - height * 2" />
      <velocity x="0" y="0" />
      <collision enabled="true" left="collide('static')" right="collide('static')" basic="collide('static')"/>
      <actions>
        <action name="left" value="move.left(step)" />
        <action name="right" value="move.right(step)" />
      </actions>				
    </object>
    <object name="bricks">
      <sprite src="grid(7,5,shape.rectangle(width,height))" />
      <position x="margin" y="margin" />
      <velocity x="0" y="0" />
      <collision enabled="true" basic="collide('die')" />
    </object>
  </objects>	
  <states>
    <state name="mainmenu">
      <shows>
        <show object="player" />
      </shows>
      <inputs>
        <input action="state.playing" button="space" />
        <input action="state.settings" button="s" />
      </inputs>
    </state>
    <state name="settings">
      <shows>
        <show object="player" />
      </shows>
      <inputs>
        <input action="state.mainmenu" button="escape" />
      </inputs>
    </state>
    <state name="playing">
      <shows>
        <show object="ball" />
        <show object="player" />
        <show object="bricks" />
      </shows>
      <inputs>
        <input action="state.paused" button="space" />
        <input action="player.action.left" button="left" />
        <input action="player.action.right" button="right" />
      </inputs>
    </state>
    <state name="paused">
      <shows>
        <show object="player" />
      </shows>
      <inputs>
        <input action="state.playing" button="space" />
      </inputs>
    </state>
  </states>
</game>

=== beefviper/XMLGameEngine/games/pong_full.xml
<!-- pong_full.xml -->
<!-- XML Game Engine -->
<!-- author: beefviper -->
<!-- date: Sept 18, 2020 -->

<game xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="assets/xmlgameengine.xsd">
  <!-- window -->
  <window name="Pong" width="1280" height="720" background="color.black" fullscreen="false" framerate="60" />
  <!-- variables -->
  <variables>
    <variable name="margin" value="30" />
    <variable name="text.size" value="256" />
    <variable name="logo.radius" value="100" />
    <variable name="ball.radius" value="10" />
    <variable name="width" value="30" />
    <variable name="height" value="150" />
    <variable name="step" value="2" />
  </variables>
  <!-- objects -->
  <objects>
    <!-- title -->
    <object name="title">
      <sprite src="text('PONG', text.size, 'color.red')" />
      <position x="window.width.center - 350" y="margin" />
      <velocity x="0" y="0" />
      <collision enabled="false" />
    </object>
    <!-- logo -->
    <object name="logo">
      <sprite src="shape.circle(logo.radius,'color.green')" />
      <position x="window.width.center - logo.radius" y="window.height.center - logo.radius" />
      <velocity x="0" y="0" />
      <collision enabled="false" />
    </object>
    <!-- ball -->
    <object name="ball">
      <sprite src="shape.circle(ball.radius,'color.green')" />
      <position x="window.width.center - ball.radius" y="window.height.center - ball.radius" />
      <velocity x="random.range(-7,7)" y="random.range(-3,3)" />
      <collision enabled="true" top="bounce()" bottom="bounce()" left="inc('score2');reset" right="inc('score1');reset()" basic="bounce()" />
    </object>
    <!-- paddle1 -->
    <object name="paddle1">
      <sprite src="image('games/assets/paddle.jpg')" />
      <position x="window.left + margin" y="window.height.center - height / 2" />
      <velocity x="0" y="0" />
      <collision enabled="true" top="stick()" bottom="stick()" />
      <actions>
        <action name="up" value="move.up(step)" />
        <action name="down" value="move.down(step)" />
      </actions>				
    </object>
    <!-- paddle2 -->
    <object name="paddle2">
      <sprite src="image('games/assets/paddle.jpg', 'flip.horizontal')" />
      <position x="window.right - margin - width" y="window.height.center - height / 2" />
      <velocity x="0" y="0" />
      <collision enabled="true" top="stick()" bottom="stick()" left="stick()" right="stick()" />
      <actions>
        <action name="up" value="move.up(step)" />
        <action name="down" value="move.down(step)" />
        <action name="left" value="move.left(step)" />
        <action name="right" value="move.right(step)" />
      </actions>				
    </object>
    <!-- score1 -->
    <object name="score1">
      <sprite src="text('0',128,'color.blue')" />
      <position x="window.width.center - 80" y="margin" />
      <velocity x="0" y="0" />
      <collision enabled="false" />
    </object>
    <!-- score2 -->
    <object name="score2">
      <sprite src="text('0',128,'color.red')" />
      <position x="window.width.center + 50" y="margin" />
      <velocity x="0" y="0" />
      <collision enabled="false" />
    </object>
  </objects>
  <!-- states -->
  <states>
    <!-- mainmenu -->
    <state name="mainmenu">
      <shows>
        <show object="title" />
        <show object="logo" />
      </shows>
      <inputs>
        <input button="space" action="state.playing" />
		<input button="s" action="state.settings" />
      </inputs>
    </state>
    <!-- settings -->
    <state name="settings">
      <shows>
        <show object="logo" />
      </shows>
      <inputs>
        <input button="escape" action="state.mainmenu" />
      </inputs>
    </state>
    <!-- playing -->
    <state name="playing">
      <shows>
        <show object="ball" />
        <show object="paddle1" />
        <show object="paddle2" />
        <show object="score1" />
        <show object="score2" />
      </shows>
      <inputs>
        <input button="space" action="state('paused')" />
		<input button="q" action="action('paddle1', 'up')" />
		<input button="z" action="action('paddle1', 'down')" />
		<input button="up" action="action('paddle2', 'up')" />
		<input button="down" action="action('paddle2', 'down')" />
		<input button="left" action="action('paddle2', 'left')" />
		<input button="right" action="action('paddle2', 'right')" />
      </inputs>
    </state>
    <!-- paused -->
    <state name="paused">
      <shows>
        <show object="logo" />
      </shows>
      <inputs>
        <input button="space" action="state('playing')"  />
      </inputs>
    </state>
  </states>
</game>

=== beefviper/XMLGameEngine/games/pong.xml
<!-- pong.xml -->
<!-- XML Game Engine -->
<!-- author: beefviper -->
<!-- date: July 13, 2021 -->

<game xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="assets/xmlgameengine.xsd">
	<!-- window -->
	<window name="Pong" width="1280" height="720" background="color.black" fullscreen="false" framerate="60" />
	<!-- variables -->
	<variables>
		<variable name="margin" value="30" />
		<variable name="text.size" value="256" />
		<variable name="logo.radius" value="100" />
		<variable name="ball.radius" value="10" />
		<variable name="width" value="30" />
		<variable name="height" value="150" />
		<variable name="step" value="2" />
	</variables>
	<!-- objects -->
	<objects>
		<!-- ball -->
		<object name="ball">
			<sprite src="shape.circle(ball.radius,'color.white')" />
			<position x="window.width.center - ball.radius" y="window.height.center - ball.radius" />
			<velocity x="random.range(-7,7)" y="random.range(-3,3)" />
			<collisions enabled="true">
				<collision edge="horizontal" action="bounce()" />
				<collision edge="left" action="inc('paddle2.score');reset()" />
				<collision edge="right" action="inc('paddle1.score');reset()" />
			</collisions>
		</object>
		<!-- paddle1 -->
		<object name="paddle1" class="paddle">
			<sprite src="shape.rectangle(width,height,'color.white')" />
			<position x="window.left + margin" y="window.height.center - height / 2" />
			<velocity x="0" y="0" />
			<collisions enabled="true">
				<collision edge="vertical" action="stick()" />
			</collisions>
			<actions>
				<action name="up" value="move.up(step)" />
				<action name="down" value="move.down(step)" />
			</actions>
			<variables>
				<variable score="0" />
			</variables>
		</object>
		<!-- paddle2 -->
		<object name="paddle2">
			<sprite src="shape.rectangle(width,height,'color.white')" />
			<position x="window.right - margin - width" y="window.height.center - height / 2" />
			<velocity x="0" y="0" />
			<collisions enabled="true">
				<collision edge="vertical" action="stick()" />
			</collisions>
			<actions>
				<action name="up" value="move.up(step)" />
				<action name="down" value="move.down(step)" />
			</actions>
			<variables>
				<variable score="0" />
			</variables>
		</object>
		<!-- score1 -->
		<object name="score1">
			<sprite src="text(paddle1.score,128,'color.white')" />
			<position x="window.width.center - 80" y="margin" />
			<velocity x="0" y="0" />
			<collisions enabled="false" />
		</object>
		<!-- score2 -->
		<object name="score2">
			<sprite src="text(paddle2.score,128,'color.white')" />
			<position x="window.width.center + 50" y="margin" />
			<velocity x="0" y="0" />
			<collisions enabled="false" />
		</object>
	</objects>
	<!-- states -->
	<states>
		<!-- playing -->
		<state name="playing">
			<shows>
				<show object="ball" />
				<show object="paddle1" />
				<show object="paddle2" />
				<show object="score1" />
				<show object="score2" />
			</shows>
			<inputs>
				<input button="q" action="action('paddle1', 'up')" />
				<input button="z" action="action('paddle1', 'down')" />
				<input button="up" action="action('paddle2', 'up')" />
				<input button="down" action="action('paddle', 'down')" />
			</inputs>
		</state>
	</states>
</game>

=== beefviper/XMLGameEngine/games/spaceinvaders.xml
<!-- spaceinvaders.xml -->
<!-- XML Game Engine -->
<!-- author: beefviper -->
<!-- date: Sept 18, 2020 -->

<game xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="assets/xmlgameengine.xsd">
  <window name="Space Invaders" width="1024" height="768" background="color.black" fullscreen="false" framerate="60" />
  <variables>
    <variable name="margin" value="80" />
    <variable name="ball.radius" value="10" />
    <variable name="width" value="50" />
    <variable name="height" value="50" />
    <variable name="step" value="2" />
  </variables>
  <objects>
    <object name="bullet" class="projectile">
      <sprite src="shape.circle(ball.radius)" />
      <position x="0" y="0" />
      <velocity x="0" y="0" />
      <collisions enabled="false">
        <collision edge="all" action="die()"/>
        <collision basic="basic" action="die()"/>
      </collisions>
      <variables>
        <variable name="speed" value="-6" />
      </variables>
    </object>
    <object name="player">
      <sprite src="shape.rectangle(width,height)" />
      <position x="window.width.center" y="window.bottom - height * 2" />
      <velocity x="0" y="0" />
      <collisions enabled="true">
        <collision edge="horizontal" action="stick()" />
      </collisions>
      <actions>
        <action name="left" value="move.left(step)" />
        <action name="right" value="move.right(step)" />
        <action name ="gun" value="fire('bullet')"/>
      </actions>
    </object>
    <object name="bricks">
      <sprite src="grid(11,5,15,15,shape.rectangle(width,height))" />
      <position x="margin" y="margin/2" />
      <velocity x="2" y="0" />
      <collisions enabled="true" group="true">
        <collision edge="horizontal" action="bounce();move.down(10)" />
        <collision basic="basic" action="die()" />
      </collisions>
    </object>
    <object name="settings">
      <sprite src="text('settings',128,'color.white')" />
      <position x="window.width.center" y="window.height.center" />
      <velocity x="0" y="0" />
      <collisions enabled="false" />
    </object>
    <object name="paused">
      <sprite src="text('paused',128,'color.white')" />
      <position x="window.width.center - 180" y="window.height.center - 200" />
      <velocity x="0" y="0" />
      <collisions enabled="false" />
    </object>
  </objects>
  <states>
    <state name="mainmenu">
      <shows>
        <show object="player" />
      </shows>
      <inputs>
        <input button="enter" action="state('playing')" />
        <input button="s" action="state('settings')" />
      </inputs>
    </state>
    <state name="settings">
      <shows>
        <show object="settings" />
        <show object="player" />
      </shows>
      <inputs>
        <input button="escape" action="state()" />
      </inputs>
    </state>
    <state name="playing">
      <shows>
        <show object="bullet" />
        <show object="player" />
        <show object="bricks" />
      </shows>
      <inputs>
        <input button="p" action="state('paused')" />
        <input button="left" action="action('player', 'left')" />
        <input button="right" action="action('player', 'right')" />
        <input button="space" action="action('player', 'gun')" />
        <input button="escape" action="state('paused')" />
      </inputs>
    </state>
    <state name="paused">
      <shows>
        <show object="paused" />
        <show object="player" />
      </shows>
      <inputs>
        <input button="p" action="state()" />
      </inputs>
    </state>
  </states>
</game>
